#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "lib/buildkite_config"

config = Buildkite::Config::Generate.new(ARGV.shift || File.expand_path("../..", __FILE__))

RUBIES = []
SOFT_FAIL = []

MASTER_RUBY = "rubylang/ruby:master-nightly-jammy"
SOFT_FAIL << MASTER_RUBY

# Adds yjit: onto the master ruby image string so we
# know when to turn on YJIT via the environment variable.
# Same as master ruby, we want this to soft fail.
YJIT_RUBY = "yjit:#{MASTER_RUBY}"
SOFT_FAIL << YJIT_RUBY

# Run steps for newer Rubies first.
SOFT_FAIL.reverse!

config.soft_fail = SOFT_FAIL

# Run soft-failing Ruby steps last.
RUBIES.concat config.soft_fail

config.default_ruby = RUBIES.last
config.rubies = RUBIES

puts config.generate
