#!/usr/bin/env ruby
# frozen_string_literal: true

def run(cmd, env = {}, value = false)
  io = IO.popen(env, cmd)
  output = io.read
  io.close

  raise output unless $?.success?

  output if value
end

env = {}

if %w[rails-ci rails-sandbox zzak/rails Rails].include?(ENV["BUILDKITE_PIPELINE_NAME"])
  env["BUNDLE_GEMFILE"] = ".buildkite/Gemfile"
end

run "bundle install", env

pipeline = run "bundle exec buildkite-builder preview rails-ci", env, true

puts pipeline
