#!/usr/bin/env ruby
# frozen_string_literal: true

require "buildkite-builder"

pipeline = Pathname.new(Dir.pwd) + "pipelines/rails-ci"
build = Buildkite::Builder::Pipeline.new pipeline

puts build.to_yaml
