#!/usr/bin/env ruby
# frozen_string_literal: true

nightly = ARGV.include?("--nightly")

def run(cmd, value = false)
  io = IO.popen(cmd)
  output = io.read
  io.close

  raise output unless $?.success?

  output if value
end

run "bundle install"

annotation = run "bundle exec rake diff#{"[true]" if nightly}", true

puts annotation
